const $ = (s) => document.querySelector(s);
const state = { files: [], batchId: null, batch: null, poll: null };
const labels = { queued:'等待处理', processing:'模型处理中', completed:'处理完成', failed:'处理失败' };

function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2400)}
async function api(url, options={}){const r=await fetch(url,options);let d;try{d=await r.json()}catch{d=null}if(!r.ok)throw new Error(d?.error||`请求失败 ${r.status}`);return d}
function route(){const review=location.hash.startsWith('#review');$('#uploadView').classList.toggle('hidden',review);$('#reviewView').classList.toggle('hidden',!review);document.querySelectorAll('[data-nav]').forEach(x=>x.classList.toggle('active',x.dataset.nav===(review?'review':'upload')));if(review){const id=new URLSearchParams(location.hash.split('?')[1]||'').get('batch')||state.batchId;if(id)openReview(id);else loadBatches()}}

const drop=$('#dropzone'), input=$('#fileInput');
drop.onclick=()=>input.click();drop.onkeydown=e=>{if(e.key==='Enter'||e.key===' ')input.click()};
drop.ondragover=e=>{e.preventDefault();drop.classList.add('drag')};drop.ondragleave=()=>drop.classList.remove('drag');
drop.ondrop=e=>{e.preventDefault();drop.classList.remove('drag');selectFiles(e.dataTransfer.files)};input.onchange=()=>selectFiles(input.files);
function selectFiles(list){state.files=[...list].filter(f=>/\.(jpe?g|png|tiff?)$/i.test(f.name));$('#selection').classList.toggle('hidden',!state.files.length);$('#selection').textContent=state.files.length?`已选择 ${state.files.length} 张 · ${(state.files.reduce((a,f)=>a+f.size,0)/1048576).toFixed(1)} MB`:'';$('#startButton').disabled=!state.files.length}

$('#startButton').onclick=async()=>{try{$('#startButton').disabled=true;const batch=await api('/api/batches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:$('#batchName').value})});state.batchId=batch.id;$('#emptyQueue').classList.add('hidden');$('#queue').classList.remove('hidden');$('#queue').innerHTML='';for(const file of state.files){addLocalQueue(file);await api(`/api/batches/${batch.id}/images?filename=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'Content-Type':file.type||'application/octet-stream'},body:file})}startPolling();toast('上传完成，模型正在处理')}catch(e){toast(e.message);$('#startButton').disabled=false}};
function addLocalQueue(file){const row=document.createElement('div');row.className='queue-item';row.dataset.name=file.name;const url=URL.createObjectURL(file);row.innerHTML=`<img class="queue-thumb" src="${url}"><div><div class="queue-name"></div><div class="queue-state">正在上传</div></div><div class="state-icon spinner">◌</div>`;row.querySelector('.queue-name').textContent=file.name;$('#queue').append(row)}
function startPolling(){clearInterval(state.poll);refreshQueue();state.poll=setInterval(refreshQueue,1200)}
async function refreshQueue(){if(!state.batchId)return;try{const b=await api(`/api/batches/${state.batchId}`);state.batch=b;$('#profileName').textContent=b.target_profile||'模型就绪';$('#queue').innerHTML=b.images.map(i=>`<div class="queue-item"><img class="queue-thumb" src="/media/${b.id}/${i.id}/input/file"><div><div class="queue-name">${escapeHtml(i.filename)}</div><div class="queue-state">${i.error?escapeHtml(i.error):labels[i.process_status]}</div></div><div class="state-icon ${i.process_status==='completed'?'done':i.process_status==='failed'?'fail':'spinner'}">${i.process_status==='completed'?'✓':i.process_status==='failed'?'!':'◌'}</div></div>`).join('');if(b.counts.processing===0){clearInterval(state.poll);$('#reviewButton').classList.remove('hidden');$('#startButton').disabled=false;loadBatches()}}catch(e){clearInterval(state.poll);toast(e.message)}}
$('#reviewButton').onclick=()=>location.hash=`review?batch=${state.batchId}`;$('#backButton').onclick=()=>location.hash='upload';

async function loadBatches(){try{const batches=await api('/api/batches');$('#batchList').innerHTML=batches.length?batches.map(b=>`<article class="batch-card" data-id="${b.id}"><h3>${escapeHtml(b.name)}</h3><p class="muted">${b.target_profile||'CMYK'} · ${b.counts.total} 张图片</p><div class="mini-progress"><span style="width:${b.counts.total?b.counts.completed/b.counts.total*100:0}%"></span></div><div class="batch-card-footer"><span>${new Date(b.created_at).toLocaleString()}</span><span>${b.counts.approved} 已通过 →</span></div></article>`).join(''):'<p class="muted">还没有处理批次</p>';document.querySelectorAll('.batch-card').forEach(x=>x.onclick=()=>location.hash=`review?batch=${x.dataset.id}`)}catch(e){toast(e.message)}}
$('#refreshBatches').onclick=loadBatches;

async function openReview(id){state.batchId=id;try{const b=await api(`/api/batches/${id}`);state.batch=b;$('#reviewTitle').textContent=b.name;$('#reviewMeta').textContent=`${b.target_profile} · 创建于 ${new Date(b.created_at).toLocaleString()}`;$('#profileName').textContent=b.target_profile;$('#downloadButton').href=`/api/batches/${id}/download?status=approved`;renderStats(b.counts);renderReview()}catch(e){toast(e.message)}}
function renderStats(c){$('#stats').innerHTML=[['总计',c.total],['待审核',c.pending],['已通过',c.approved],['已驳回',c.rejected],['处理失败',c.failed]].map(([n,v])=>`<div class="stat"><strong>${v}</strong><span>${n}</span></div>`).join('')}
function renderReview(){const filter=$('#statusFilter').value;const items=state.batch.images.filter(i=>filter==='all'||i.review_status===filter);$('#noReview').classList.toggle('hidden',items.length>0);$('#reviewGrid').innerHTML=items.map(i=>i.process_status==='completed'?card(i):`<article class="review-card processing-card"><div><strong>${escapeHtml(i.filename)}</strong><p>${i.error||labels[i.process_status]}</p></div></article>`).join('');document.querySelectorAll('.compare input').forEach(sl=>sl.oninput=()=>sl.parentElement.style.setProperty('--split',`${sl.value}%`));document.querySelectorAll('.decision').forEach(b=>b.onclick=()=>reviewItem(b.dataset.id,b.dataset.status));document.querySelectorAll('.note').forEach(n=>n.onchange=()=>reviewItem(n.dataset.id,state.batch.images.find(x=>x.id===n.dataset.id).review_status,n.value))}
function card(i){return `<article class="review-card ${i.review_status}"><div class="compare"><img src="/media/${state.batch.id}/${i.id}/input/file"><img class="after" src="/media/${state.batch.id}/${i.id}/preview/file"><div class="divider"></div><span class="compare-label before-label">原图 RGB</span><span class="compare-label after-label">输出 CMYK</span><input type="range" min="0" max="100" value="50" aria-label="拖动比较"></div><div class="card-body"><div class="card-head"><h3 title="${escapeHtml(i.filename)}">${escapeHtml(i.filename)}</h3><span>${i.width} × ${i.height}</span></div><textarea class="note" data-id="${i.id}" rows="1" placeholder="添加审核备注…">${escapeHtml(i.note||'')}</textarea><div class="decision-row"><button data-id="${i.id}" data-status="approved" class="decision approve ${i.review_status==='approved'?'active':''}">✓ 通过</button><button data-id="${i.id}" data-status="rejected" class="decision reject ${i.review_status==='rejected'?'active':''}">× 驳回</button></div></div></article>`}
async function reviewItem(id,status,note){try{const item=state.batch.images.find(x=>x.id===id);await api(`/api/batches/${state.batch.id}/${id}/review`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status,note:note??item.note})});await openReview(state.batch.id);toast(status==='approved'?'已标记为通过':status==='rejected'?'已标记为驳回':'备注已保存')}catch(e){toast(e.message)}}
$('#statusFilter').onchange=renderReview;
function escapeHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
window.addEventListener('hashchange',route);loadBatches();route();
